name: build-and-deploy

on:
  workflow_dispatch:

# Apparently "write" also implies "read" ...
permissions:
  contents: write
  pages: write
  id-token: write

# Skip runs queued between in-progress and latest, but don't cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Pulls changes from Drive and commits
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Init Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
        
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Download & Parse Drive Content
        run: python scripts/fetch_drive_contents.py
      
      - name: Check whether to commit files in content/
        id: check_config
        run: |
          if grep -q 'commit-static-html: false' _config.yml; then
            echo "commitstatic=true" >> $GITHUB_ENV
          else
            echo "commitstatic=false" >> $GITHUB_ENV
          fi

      - name: Commit static pages if requested in _config.yml
        if: env.commitstatic == 'true'
        run: |
          git add content/
          git config --global user.name '${{ github.actor }} - Automated'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -am "Automated commit from build-and-deploy workflow"
          git push
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'content/'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4