name: Update Website Builder

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add the original repository as an upstream remote
      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/Rachmanin0xFF/docs-to-pages.git || echo "Upstream already exists"
          git fetch upstream

      # Merge updates
      - name: Merge updates
        run: |
          git checkout --ours CONFIG.ini
          git checkout --ours LINK_TO_DRIVE_FOLDER
          git add CONFIG.ini
          git add LINK_TO_DRIVE_FOLDER
          git merge upstream/main --allow-unrelated-histories -m "Merge updates from template"

      - name: Push changes
        run: |
          git push origin main